class InvitationCardRunner {


	public static void main(String[] card) {

		InvitationCard ref1 = new InvitationCard();
		ref1.cardId = 1;
		ref1.occasion = "Wedding";
		ref1.sender = "Ravi";
		ref1.receiver = "Arjun";
		ref1.date = "10-Aug-2025";
		ref1.venue = " Mysore";
		System.out.println("the card id is " + ref1.cardId);
		System.out.println("the occasion is " + ref1.occasion);
		System.out.println("the sender is " + ref1.sender);
		System.out.println("the receiver is " + ref1.receiver);
		System.out.println("the date is " + ref1.date);
		System.out.println("the venue is " + ref1.venue);

		InvitationCard ref2 = new InvitationCard();
		ref2.cardId = 2;
		ref2.occasion = "Birthday";
		ref2.sender = "Kavya";
		ref2.receiver = "Neha";
		ref2.date = "12-Jul-2025";
		ref2.venue = "Bengaluru";
		System.out.println("the card id is " + ref2.cardId);
		System.out.println("the occasion is " + ref2.occasion);
		System.out.println("the sender is " + ref2.sender);
		System.out.println("the receiver is " + ref2.receiver);
		System.out.println("the date is " + ref2.date);
		System.out.println("the venue is " + ref2.venue);

		InvitationCard ref3 = new InvitationCard();
		ref3.cardId = 3;
		ref3.occasion = "Anniversary";
		ref3.sender = "Anil & Meena";
		ref3.receiver = "Relatives";
		ref3.date = "20-Nov-2025";
		ref3.venue = "Chennai";
		System.out.println("the card id is " + ref3.cardId);
		System.out.println("the occasion is " + ref3.occasion);
		System.out.println("the sender is " + ref3.sender);
		System.out.println("the receiver is " + ref3.receiver);
		System.out.println("the date is " + ref3.date);
		System.out.println("the venue is " + ref3.venue);

		InvitationCard ref4 = new InvitationCard();
		ref4.cardId = 4;
		ref4.occasion = "Engagement";
		ref4.sender = "Suresh";
		ref4.receiver = "Friends";
		ref4.date = "05-Oct-2025";
		ref4.venue = "Hyderabad";
		System.out.println("the card id is " + ref4.cardId);
		System.out.println("the occasion is " + ref4.occasion);
		System.out.println("the sender is " + ref4.sender);
		System.out.println("the receiver is " + ref4.receiver);
		System.out.println("the date is " + ref4.date);
		System.out.println("the venue is " + ref4.venue);

		InvitationCard ref5 = new InvitationCard();
		ref5.cardId = 5;
		ref5.occasion = "Housewarming";
		ref5.sender = "Rachana";
		ref5.receiver = "Family";
		ref5.date = "01-Sep-2025";
		ref5.venue = "Pune";
		System.out.println("the card id is " + ref5.cardId);
		System.out.println("the occasion is " + ref5.occasion);
		System.out.println("the sender is " + ref5.sender);
		System.out.println("the receiver is " + ref5.receiver);
		System.out.println("the date is " + ref5.date);
		System.out.println("the venue is " + ref5.venue);

		InvitationCard ref6 = new InvitationCard();
		ref6.cardId = 6;
		ref6.occasion = "Baby Shower";
		ref6.sender = "Divya";
		ref6.receiver = "Sisters";
		ref6.date = "15-Aug-2025";
		ref6.venue = "Mumbai";
		System.out.println("the card id is " + ref6.cardId);
		System.out.println("the occasion is " + ref6.occasion);
		System.out.println("the sender is " + ref6.sender);
		System.out.println("the receiver is " + ref6.receiver);
		System.out.println("the date is " + ref6.date);
		System.out.println("the venue is " + ref6.venue);

		InvitationCard ref7 = new InvitationCard();
		ref7.cardId = 7;
		ref7.occasion = "Retirement";
		ref7.sender = "Mr. Ramesh";
		ref7.receiver = "Colleagues";
		ref7.date = "30-Jul-2025";
		ref7.venue = "Bengaluru";
		System.out.println("the card id is " + ref7.cardId);
		System.out.println("the occasion is " + ref7.occasion);
		System.out.println("the sender is " + ref7.sender);
		System.out.println("the receiver is " + ref7.receiver);
		System.out.println("the date is " + ref7.date);
		System.out.println("the venue is " + ref7.venue);

		InvitationCard ref8 = new InvitationCard();
		ref8.cardId = 8;
		ref8.occasion = "Farewell";
		ref8.sender = "BCA Batch 2022";
		ref8.receiver = "Seniors";
		ref8.date = "25-Jul-2025";
		ref8.venue = "coolage";
		System.out.println("the card id is " + ref8.cardId);
		System.out.println("the occasion is " + ref8.occasion);
		System.out.println("the sender is " + ref8.sender);
		System.out.println("the receiver is " + ref8.receiver);
		System.out.println("the date is " + ref8.date);
		System.out.println("the venue is " + ref8.venue);

		InvitationCard ref9 = new InvitationCard();
		ref9.cardId = 9;
		ref9.occasion = "Graduation";
		ref9.sender = "Management";
		ref9.receiver = "Students";
		ref9.date = "01-Apr-2025";
		ref9.venue = "Bengaluru";
		System.out.println("the card id is " + ref9.cardId);
		System.out.println("the occasion is " + ref9.occasion);
		System.out.println("the sender is " + ref9.sender);
		System.out.println("the receiver is " + ref9.receiver);
		System.out.println("the date is " + ref9.date);
		System.out.println("the venue is " + ref9.venue);

		InvitationCard ref10 = new InvitationCard();
		ref10.cardId = 10;
		ref10.occasion = "Naming Ceremony";
		ref10.sender = "Suman & Rajesh";
		ref10.receiver = "Neighbors";
		ref10.date = "09-Sep-2025";
		ref10.venue = "Bengaluru";
		System.out.println("the card id is " + ref10.cardId);
		System.out.println("the occasion is " + ref10.occasion);
		System.out.println("the sender is " + ref10.sender);
		System.out.println("the receiver is " + ref10.receiver);
		System.out.println("the date is " + ref10.date);
		System.out.println("the venue is " + ref10.venue);
		
				InvitationCard ref11 = new InvitationCard();
		ref11.cardId = 11;
		ref11.occasion = "Inauguration";
		ref11.sender = "Dr. Sharma";
		ref11.receiver = "Guests";
		ref11.date = "18-Aug-2025";
		ref11.venue = "Delhi";
		System.out.println("the card id is " + ref11.cardId);
		System.out.println("the occasion is " + ref11.occasion);
		System.out.println("the sender is " + ref11.sender);
		System.out.println("the receiver is " + ref11.receiver);
		System.out.println("the date is " + ref11.date);
		System.out.println("the venue is " + ref11.venue);

		InvitationCard ref12 = new InvitationCard();
		ref12.cardId = 12;
		ref12.occasion = "Cultural Fest";
		ref12.sender = "Student Council";
		ref12.receiver = "All Students";
		ref12.date = "22-Sep-2025";
		ref12.venue = "College";
		System.out.println("the card id is " + ref12.cardId);
		System.out.println("the occasion is " + ref12.occasion);
		System.out.println("the sender is " + ref12.sender);
		System.out.println("the receiver is " + ref12.receiver);
		System.out.println("the date is " + ref12.date);
		System.out.println("the venue is " + ref12.venue);

		InvitationCard ref13 = new InvitationCard();
		ref13.cardId = 13;
		ref13.occasion = "Music Concert";
		ref13.sender = "Event Team";
		ref13.receiver = "Music Lovers";
		ref13.date = "01-Oct-2025";
		ref13.venue = "Kolkata";
		System.out.println("the card id is " + ref13.cardId);
		System.out.println("the occasion is " + ref13.occasion);
		System.out.println("the sender is " + ref13.sender);
		System.out.println("the receiver is " + ref13.receiver);
		System.out.println("the date is " + ref13.date);
		System.out.println("the venue is " + ref13.venue);

		InvitationCard ref14 = new InvitationCard();
		ref14.cardId = 14;
		ref14.occasion = "Graduation Party";
		ref14.sender = "Final Year Students";
		ref14.receiver = "Batchmates";
		ref14.date = "15-May-2025";
		ref14.venue = "Goa";
		System.out.println("the card id is " + ref14.cardId);
		System.out.println("the occasion is " + ref14.occasion);
		System.out.println("the sender is " + ref14.sender);
		System.out.println("the receiver is " + ref14.receiver);
		System.out.println("the date is " + ref14.date);
		System.out.println("the venue is " + ref14.venue);

		InvitationCard ref15 = new InvitationCard();
		ref15.cardId = 15;
		ref15.occasion = "Reception";
		ref15.sender = "Ritika & Aman";
		ref15.receiver = "Friends & Family";
		ref15.date = "25-Dec-2025";
		ref15.venue = "Delhi";
		System.out.println("the card id is " + ref15.cardId);
		System.out.println("the occasion is " + ref15.occasion);
		System.out.println("the sender is " + ref15.sender);
		System.out.println("the receiver is " + ref15.receiver);
		System.out.println("the date is " + ref15.date);
		System.out.println("the venue is " + ref15.venue);

		InvitationCard ref16 = new InvitationCard();
		ref16.cardId = 16;
		ref16.occasion = "Sports Meet";
		ref16.sender = "Sports Committee";
		ref16.receiver = "Athletes";
		ref16.date = "08-Feb-2025";
		ref16.venue = "Bhopal";
		System.out.println("the card id is " + ref16.cardId);
		System.out.println("the occasion is " + ref16.occasion);
		System.out.println("the sender is " + ref16.sender);
		System.out.println("the receiver is " + ref16.receiver);
		System.out.println("the date is " + ref16.date);
		System.out.println("the venue is " + ref16.venue);

		InvitationCard ref17 = new InvitationCard();
		ref17.cardId = 17;
		ref17.occasion = "Alumni Meet";
		ref17.sender = "Alumni Association";
		ref17.receiver = "Former Students";
		ref17.date = "20-Mar-2025";
		ref17.venue = "Institute";
		System.out.println("the card id is " + ref17.cardId);
		System.out.println("the occasion is " + ref17.occasion);
		System.out.println("the sender is " + ref17.sender);
		System.out.println("the receiver is " + ref17.receiver);
		System.out.println("the date is " + ref17.date);
		System.out.println("the venue is " + ref17.venue);

		InvitationCard ref18 = new InvitationCard();
		ref18.cardId = 18;
		ref18.occasion = "Book Launch";
		ref18.sender = "Author Society";
		ref18.receiver = "Readers";
		ref18.date = "12-Jan-2025";
		ref18.venue = "Jaipur";
		System.out.println("the card id is " + ref18.cardId);
		System.out.println("the occasion is " + ref18.occasion);
		System.out.println("the sender is " + ref18.sender);
		System.out.println("the receiver is " + ref18.receiver);
		System.out.println("the date is " + ref18.date);
		System.out.println("the venue is " + ref18.venue);

		InvitationCard ref19 = new InvitationCard();
		ref19.cardId = 19;
		ref19.occasion = "Kit Distribution";
		ref19.sender = "NGO Samarth";
		ref19.receiver = "Beneficiaries";
		ref19.date = "07-Jun-2025";
		ref19.venue = "Ranchi";
		System.out.println("the card id is " + ref19.cardId);
		System.out.println("the occasion is " + ref19.occasion);
		System.out.println("the sender is " + ref19.sender);
		System.out.println("the receiver is " + ref19.receiver);
		System.out.println("the date is " + ref19.date);
		System.out.println("the venue is " + ref19.venue);

		InvitationCard ref20 = new InvitationCard();
		ref20.cardId = 20;
		ref20.occasion = "Festival Celebration";
		ref20.sender = "Community Group";
		ref20.receiver = "All Residents";
		ref20.date = "04-Nov-2025";
		ref20.venue = "Ahmedabad";
		System.out.println("the card id is " + ref20.cardId);
		System.out.println("the occasion is " + ref20.occasion);
		System.out.println("the sender is " + ref20.sender);
		System.out.println("the receiver is " + ref20.receiver);
		System.out.println("the date is " + ref20.date);
		System.out.println("the venue is " + ref20.venue);
	}
}
